apiVersion: apps/v1
kind: Deployment
metadata: { name: api }
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - configMapRef: { name: app-config }
            - secretRef:    { name: app-secrets }
          env:
            - name: DATABASE_URL
              value: postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)
