services:
  nestjs-app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./nestjs-app:/app
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3002:3001"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/nestjsdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - prometheus

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjsdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
